site_name: AirSim
site_dir: build_docs
repo_url: https://github.com/microsoft/airsim
site_description: 'Open source simulator based on Unreal Engine for autonomous vehicles from Microsoft AI & Research'

markdown_extensions:
    - toc:
        permalink: "#"
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.extra:
    - admonition

remote_branch: gh-pages

theme:
  name: 'readthedocs'
  logo: ''

extra:
  highlightjs: true
  version: master
  feature:
      tabs: true
  palette:
  social:
      - type: facebook
        link: https://www.facebook.com/groups/1225832467530667/
      - type: github-alt
        link: https://github.com/Microsoft/AirSim

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2021 Microsoft Research

nav:
  - "主页":
    - "主页": 'README.md'
  - "修改记录": 'CHANGELOG.md'
  - "构建 AirSim":
    - "下载二进制文件": 'use_precompiled.md'
    - "在 Windows 上构建": 'build_windows.md'
    - "在 Linux 上构建": 'build_linux.md'
    - "在 macOS 上构建": 'build_macos.md'
    - "Linux 上的 Docker": 'docker_ubuntu.md'
    - "Azure 上的 ArSim": 'azure.md'
    - "定制虚幻引擎环境": 'unreal_custenv.md'
    - "场景问题和回答": 'build_faq.md'
  - "使用 AirSim":
    - "核心 APIs": 'apis.md'
    - "图像 APIs": 'image_apis.md'
    - "C++ APIs": 'apis_cpp.md'
    - "API 参考文档": 'api_docs/html/index.html'
    - "开发工作流": 'dev_workflow.md'
    - "设置": 'settings.md'
    - "相机视角": 'camera_views.md'
    - "汽车模式": 'using_car.md'
    - "远程控制": 'remote_control.md'
    - "XBox 控制器": 'xbox_controller.md'
    - "方向盘": 'steering_wheel_installation.md'
    - "多车辆": 'multi_vehicle.md'
    - "传感器":
      - "传感器": 'sensors.md'
      - "激光雷达": 'lidar.md'
      - "距离传感器": 'distance_sensor.md'
      - "红外相机": "InfraredCamera.md"
    - "ROS: AirSim ROS 包装器": "airsim_ros_pkgs.md"
    - "ROS: AirSim 教程包": "airsim_tutorial_pkgs.md"
    - "导入 Gazebo 模型": "gazebo_drone.md"
    - "域随机化": "retexturing.md"
    - "网格顶点缓冲区": "meshes.md"
    - "播放日志": 'playback.md'
    - "体素网格生成器": "voxel_grid.md"
    - "事件相机" : "event_sim.md"
  - "设计":
    - "架构": 'design.md'
    - "代码结构": 'code_structure.md'
    - "添加新的 APIs": 'adding_new_apis.md'
    - "修改记录数据": 'modify_recording_data.md'
    - "编码指南": 'coding_guidelines.md'
    - "飞行控制器": 'flight_controller.md'
    - "简单飞行": 'simple_flight.md'
    - "Hello Drone": 'hello_drone.md'
  - "外部飞行控制器":
    - "MavLink 和 PX4":
      - "AirSim 的 PX4 设置": 'px4_setup.md'
      - "软件在环中的 PX4": 'px4_sitl.md'
      - "带有 WSL 2 的 PX4 SITL": 'px4_sitl_wsl2.md'
      - "PX4 Lockstep": 'px4_lockstep.md'
      - "软件在环中的 PX4 多车辆": 'px4_multi_vehicle.md'
      - "AirSim 与 Pixhawk": 'https://youtu.be/1oY8Qu5maQQ'
      - "使用 AirSim 设置 PX4": 'https://youtu.be/HNWdYrtw3f0'
      - "调试姿态估计": 'https://www.youtube.com/watch?v=d_FyjKDWQfc&feature=youtu.be'
      - "拦截 MavLink 消息": 'https://github.com/Microsoft/AirSim/wiki/Intercepting-MavLink-messages'
      - "PX4 无人机快速下降": 'https://github.com/Microsoft/AirSim/wiki/Rapid-Descent-on-PX4-drones'
      - "构建 PX4": "px4_build.md"
      - "PX4/MavLink 日志记录": 'px4_logging.md'
      - "MavLink 日志查看器": "log_viewer.md"
      - "MavLinkCom": 'mavlinkcom.md'
      - "MavLink MoCap": 'mavlinkcom_mocap.md'
    - "ArduPilot":
      - "ArduPilot 软件在环设置": "https://ardupilot.org/dev/docs/building-the-code.html"
      - "AirSim & ArduPilot": "https://ardupilot.org/dev/docs/sitl-with-airsim.html"
  - "升级":
    - "升级虚幻引擎": 'unreal_upgrade.md'
    - "升级 APIs": 'upgrade_apis.md'
    - "升级设置": 'upgrade_settings.md'
  - "贡献教程":
    - "强化学习": 'reinforcement_learning.md'
    - "使用 Marketplace 中的环境": 'https://www.youtube.com/watch?v=y09VbdQWvQY'
    - "简单的防撞": 'https://github.com/simondlevy/AirSimTensorFlow'
    - "Azure 上的自动驾驶": 'https://aka.ms/AutonomousDrivingCookbook'
    - "建造六旋翼直升机": 'https://github.com/Microsoft/AirSim/wiki/hexacopter'
    - "移动路径演示": 'https://github.com/Microsoft/AirSim/wiki/moveOnPath-demo'
    - "构建点云": 'point_clouds.md'
    - "使用无人机进行测量": 'drone_survey.md'
    - "轨道轨迹": "orbit.md"
    - "导入自定义多旋翼网格": 'https://youtu.be/Bp86WiLUC80'
    - "Object Detection": "object_detection.md"
    - "带有 MAVROS 和 PX4 的 AirSim": 'https://youtu.be/ZonkdMcwXH4'
  - "杂项":
    - "真实无人机上的 AirSim": 'custom_drone.md'
    - "在 Linux 上安装 cmake": 'cmake_linux.md'
    - "硬盘繁忙时的提示": 'hard_drive.md'
    - "pfm 格式": 'pfm.md'
    - "设置虚幻引擎环境": 'unreal_proj.md'
    - "Blocks 环境": 'unreal_blocks.md'
    - "谁在使用 AirSim": 'who_is_using.md'
    - "使用 UE 插件内容": 'working_with_plugin_contents.md'
    - "大学生方程式赛车以色列理工学院自驾赛": 'https://github.com/Microsoft/AirSim/wiki/technion'
  - "支持":
    - "FAQ": 'faq.md'
    - "支持": 'SUPPORT.md'
    - "创建问题": 'create_issue.md'
    - "贡献": 'CONTRIBUTING.md'
